# Generated by Django 3.2.8 on 2024-03-25 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.IntegerField(default=2024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seed1', models.IntegerField()),
                ('seed2', models.IntegerField()),
                ('round', models.IntegerField(choices=[(1, 'FIRST_FOUR'), (2, 'ROUND_OF_64'), (3, 'ROUND_OF_32'), (4, 'SWEET_SIXTEEN'), (5, 'ELITE_EIGHT'), (6, 'FINAL_FOUR'), (7, 'CHAMPIONSHIP')])),
                ('year', models.IntegerField()),
                ('game_number', models.IntegerField()),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='backend.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('true_seed', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024, unique=True)),
                ('seeds', models.ManyToManyField(to='backend.Seed')),
            ],
        ),
        migrations.AddField(
            model_name='seed',
            name='seed_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.seedlist'),
        ),
        migrations.AddField(
            model_name='seed',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='backend.bracket')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
                ('predicted_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='backend.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='backend.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='backend.team'),
        ),
        migrations.AlterUniqueTogether(
            name='seed',
            unique_together={('true_seed', 'seed_list')},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('bracket', 'game_number')},
        ),
    ]
