# Generated by Django 5.1.6 on 2025-03-20 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=20)),
                ("mascot", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(default="My Bracket", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("year", models.IntegerField(default=2025)),
                (
                    "name",
                    models.CharField(default="NCAA March Madness", max_length=100),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("year", "name")},
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round",
                    models.IntegerField(
                        choices=[
                            (0, "First Four"),
                            (1, "Round of 64"),
                            (2, "Round of 32"),
                            (3, "Sweet 16"),
                            (4, "Elite Eight"),
                            (5, "Final Four"),
                            (6, "Championship"),
                        ]
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("EAST", "East"),
                            ("WEST", "West"),
                            ("MIDWEST", "Midwest"),
                            ("SOUTH", "South"),
                            ("FIRST_FOUR", "First Four"),
                        ],
                        max_length=20,
                    ),
                ),
                ("game_number", models.IntegerField()),
                ("seed1", models.IntegerField(blank=True, null=True)),
                ("seed2", models.IntegerField(blank=True, null=True)),
                ("score1", models.IntegerField(blank=True, null=True)),
                ("score2", models.IntegerField(blank=True, null=True)),
                ("game_date", models.DateTimeField(null=True)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bracket_iq.bracket",
                    ),
                ),
                (
                    "next_game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bracket_iq.game",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team1_games",
                        to="bracket_iq.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team2_games",
                        to="bracket_iq.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_won",
                        to="bracket_iq.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bracket_iq.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["tournament", "round", "game_number"],
            },
        ),
        migrations.AddField(
            model_name="bracket",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bracket_iq.tournament"
            ),
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="bracket_iq.bracket",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="bracket_iq.game",
                    ),
                ),
                (
                    "predicted_winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bracket_iq.team",
                    ),
                ),
            ],
            options={
                "ordering": ["game__round", "game__game_number"],
                "unique_together": {("game", "bracket")},
            },
        ),
        migrations.CreateModel(
            name="BracketGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1_seed", models.IntegerField(blank=True, null=True)),
                ("team2_seed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bracket_games",
                        to="bracket_iq.bracket",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bracket_games",
                        to="bracket_iq.game",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bracket_games_team1",
                        to="bracket_iq.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bracket_games_team2",
                        to="bracket_iq.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bracket_games_won",
                        to="bracket_iq.team",
                    ),
                ),
            ],
            options={
                "ordering": ["game__game_number"],
                "unique_together": {("bracket", "game")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="bracket",
            unique_together={("tournament", "user", "name")},
        ),
    ]
