#!/bin/bash
script_base=$(dirname "$0")
source $script_base/tools
cd $script_base/..

echo "Running code formatting..."
black bracket_iq

echo "Running checks..."
flake8 bracket_iq --count --select=E9,F63,F7,F82 --show-source --statistics

exit 0 