# backend/backend/management/commands/seed_teams.py
from django.core.management.base import BaseCommand
from bracket_iq.models import Team


class Command(BaseCommand):
    help = "Seeds the database with team data"

    def handle(self, *args, **options):
        # Dictionary of team data with full name as key and tuple of (short_name, mascot) as value
        team_data = {
            "Abilene Christian University": ("ACU", "Wildcats"),
            "Air Force": ("Air Force", "Falcons"),
            "Akron": ("Akron", "Zips"),
            "Alabama": ("Alabama", "Crimson Tide"),
            "Alabama A&M": ("AAMU", "Bulldogs"),
            "Alabama State": ("ASU", "Hornets"),
            "Albany": ("Albany", "Great Danes"),
            "Alcorn State": ("Alcorn", "Braves"),
            "American University": ("American", "Eagles"),
            "Appalachian State": ("App State", "Mountaineers"),
            "Arizona": ("Arizona", "Wildcats"),
            "Arizona State": ("ASU", "Sun Devils"),
            "Arkansas": ("Arkansas", "Razorbacks"),
            "Arkansas State": ("Ark State", "Red Wolves"),
            "Arkansas–Pine Bluff": ("UAPB", "Golden Lions"),
            "Army": ("Army", "Black Knights"),
            "Auburn": ("Auburn", "Tigers"),
            "Austin Peay": ("APSU", "Governors"),
            "Ball State": ("Ball St", "Cardinals"),
            "Baylor": ("Baylor", "Bears"),
            "Belmont": ("Belmont", "Bruins"),
            "Bethune–Cookman": ("BCU", "Wildcats"),
            "Binghamton": ("Binghamton", "Bearcats"),
            "Boise State": ("Boise St", "Broncos"),
            "Boston College": ("BC", "Eagles"),
            "Boston University": ("BU", "Terriers"),
            "Bowling Green": ("BGSU", "Falcons"),
            "Bradley": ("Bradley", "Braves"),
            "Brown": ("Brown", "Bears"),
            "Bryant": ("Bryant", "Bulldogs"),
            "Bucknell": ("Bucknell", "Bison"),
            "Buffalo": ("Buffalo", "Bulls"),
            "Butler": ("Butler", "Bulldogs"),
            "BYU": ("BYU", "Cougars"),
            "Cal Poly": ("Cal Poly", "Mustangs"),
            "Cal State Bakersfield": ("CSUB", "Roadrunners"),
            "Cal State Fullerton": ("CSF", "Titans"),
            "Cal State Northridge": ("CSUN", "Matadors"),
            "California": ("Cal", "Golden Bears"),
            "California Baptist": ("CBU", "Lancers"),
            "Campbell": ("Campbell", "Fighting Camels"),
            "Canisius": ("Canisius", "Golden Griffins"),
            "Central Arkansas": ("UCA", "Bears"),
            "Central Connecticut": ("CCSU", "Blue Devils"),
            "Central Michigan": ("CMU", "Chippewas"),
            "Charleston Southern": ("CSU", "Buccaneers"),
            "Charlotte": ("Charlotte", "49ers"),
            "Chattanooga": ("UTC", "Mocs"),
            "Chicago State": ("CSU", "Cougars"),
            "Cincinnati": ("Cincinnati", "Bearcats"),
            "Citadel": ("Citadel", "Bulldogs"),
            "Clemson": ("Clemson", "Tigers"),
            "Cleveland State": ("CSU", "Vikings"),
            "Coastal Carolina": ("CCU", "Chanticleers"),
            "Colgate": ("Colgate", "Raiders"),
            "College of Charleston": ("Charleston", "Cougars"),
            "Colorado": ("Colorado", "Buffaloes"),
            "Colorado State": ("CSU", "Rams"),
            "Columbia": ("Columbia", "Lions"),
            "Connecticut": ("UConn", "Huskies"),
            "Coppin State": ("Coppin St", "Eagles"),
            "Cornell": ("Cornell", "Big Red"),
            "Creighton": ("Creighton", "Bluejays"),
            "Dartmouth": ("Dartmouth", "Big Green"),
            "Davidson": ("Davidson", "Wildcats"),
            "Dayton": ("Dayton", "Flyers"),
            "Delaware": ("Delaware", "Blue Hens"),
            "Delaware State": ("DSU", "Hornets"),
            "Denver": ("Denver", "Pioneers"),
            "DePaul": ("DePaul", "Blue Demons"),
            "Detroit Mercy": ("Detroit", "Titans"),
            "Drake": ("Drake", "Bulldogs"),
            "Drexel": ("Drexel", "Dragons"),
            "Duke": ("Duke", "Blue Devils"),
            "Duquesne": ("Duquesne", "Dukes"),
            "East Carolina": ("ECU", "Pirates"),
            "East Tennessee State": ("ETSU", "Buccaneers"),
            "Eastern Illinois": ("EIU", "Panthers"),
            "Eastern Kentucky": ("EKU", "Colonels"),
            "Eastern Michigan": ("EMU", "Eagles"),
            "Eastern Washington": ("EWU", "Eagles"),
            "Elon": ("Elon", "Phoenix"),
            "Evansville": ("Evansville", "Purple Aces"),
            "Fairfield": ("Fairfield", "Stags"),
            "Fairleigh Dickinson": ("FDU", "Knights"),
            "Florida": ("Florida", "Gators"),
            "Florida A&M": ("FAMU", "Rattlers"),
            "Florida Atlantic": ("FAU", "Owls"),
            "Florida Gulf Coast": ("FGCU", "Eagles"),
            "Florida International": ("FIU", "Panthers"),
            "Florida State": ("FSU", "Seminoles"),
            "Fordham": ("Fordham", "Rams"),
            "Fresno State": ("Fresno St", "Bulldogs"),
            "Furman": ("Furman", "Paladins"),
            "Gardner–Webb": ("Gardner-Webb", "Runnin' Bulldogs"),
            "George Mason": ("Mason", "Patriots"),
            "George Washington": ("GW", "Colonials"),
            "Georgetown": ("Georgetown", "Hoyas"),
            "Georgia": ("Georgia", "Bulldogs"),
            "Georgia Southern": ("Ga Southern", "Eagles"),
            "Georgia State": ("GSU", "Panthers"),
            "Georgia Tech": ("Ga Tech", "Yellow Jackets"),
            "Gonzaga": ("Gonzaga", "Bulldogs"),
            "Grambling State": ("Grambling", "Tigers"),
            "Grand Canyon": ("GCU", "Antelopes"),
            "Green Bay": ("Green Bay", "Phoenix"),
            "Hampton": ("Hampton", "Pirates"),
            "Hartford": ("Hartford", "Hawks"),
            "Harvard": ("Harvard", "Crimson"),
            "Hawaii": ("Hawaii", "Rainbow Warriors"),
            "High Point": ("High Point", "Panthers"),
            "Hofstra": ("Hofstra", "Pride"),
            "Holy Cross": ("Holy Cross", "Crusaders"),
            "Houston": ("Houston", "Cougars"),
            "Houston Baptist": ("HBU", "Huskies"),
            "Howard": ("Howard", "Bison"),
            "Idaho": ("Idaho", "Vandals"),
            "Idaho State": ("Idaho St", "Bengals"),
            "Illinois": ("Illinois", "Fighting Illini"),
            "Illinois State": ("Illinois St", "Redbirds"),
            "Illinois–Chicago": ("UIC", "Flames"),
            "Incarnate Word": ("UIW", "Cardinals"),
            "Indiana": ("Indiana", "Hoosiers"),
            "Indiana State": ("Indiana St", "Sycamores"),
            "Iona": ("Iona", "Gaels"),
            "Iowa": ("Iowa", "Hawkeyes"),
            "Iowa State": ("Iowa St", "Cyclones"),
            "IUPUI": ("IUPUI", "Jaguars"),
            "Jackson State": ("JSU", "Tigers"),
            "Jacksonville": ("Jacksonville", "Dolphins"),
            "Jacksonville State": ("JSU", "Gamecocks"),
            "James Madison": ("JMU", "Dukes"),
            "Kansas": ("Kansas", "Jayhawks"),
            "Kansas State": ("K-State", "Wildcats"),
            "Kennesaw State": ("KSU", "Owls"),
            "Kent State": ("Kent St", "Golden Flashes"),
            "Kentucky": ("Kentucky", "Wildcats"),
            "La Salle": ("La Salle", "Explorers"),
            "Lafayette": ("Lafayette", "Leopards"),
            "Lamar": ("Lamar", "Cardinals"),
            "Lehigh": ("Lehigh", "Mountain Hawks"),
            "Liberty": ("Liberty", "Flames"),
            "Lipscomb": ("Lipscomb", "Bisons"),
            "Long Beach State": ("LBSU", "Beach"),
            "Long Island University": ("LIU", "Sharks"),
            "Longwood": ("Longwood", "Lancers"),
            "Louisiana": ("Louisiana", "Ragin' Cajuns"),
            "Louisiana Tech": ("LA Tech", "Bulldogs"),
            "Louisiana–Monroe": ("ULM", "Warhawks"),
            "Louisville": ("Louisville", "Cardinals"),
            "Loyola (MD)": ("Loyola MD", "Greyhounds"),
            "Loyola (IL)": ("Loyola Chi", "Ramblers"),
            "Loyola Marymount": ("LMU", "Lions"),
            "LSU": ("LSU", "Tigers"),
            "Maine": ("Maine", "Black Bears"),
            "Manhattan": ("Manhattan", "Jaspers"),
            "Marist": ("Marist", "Red Foxes"),
            "Marquette": ("Marquette", "Golden Eagles"),
            "Marshall": ("Marshall", "Thundering Herd"),
            "Maryland": ("Maryland", "Terrapins"),
            "Maryland Eastern Shore": ("UMES", "Hawks"),
            "UMass Lowell": ("UMass Low", "River Hawks"),
            "McNeese State": ("McNeese", "Cowboys"),
            "Memphis": ("Memphis", "Tigers"),
            "Mercer": ("Mercer", "Bears"),
            "Merrimack": ("Merrimack", "Warriors"),
            "Miami (FL)": ("Miami", "Hurricanes"),
            "Miami (OH)": ("Miami OH", "RedHawks"),
            "Michigan": ("Michigan", "Wolverines"),
            "Michigan State": ("Michigan St", "Spartans"),
            "Middle Tennessee": ("MTSU", "Blue Raiders"),
            "Milwaukee": ("Milwaukee", "Panthers"),
            "Minnesota": ("Minnesota", "Golden Gophers"),
            "Mississippi": ("Ole Miss", "Rebels"),
            "Mississippi State": ("Miss St", "Bulldogs"),
            "Mississippi Valley State": ("MVSU", "Delta Devils"),
            "Missouri": ("Missouri", "Tigers"),
            "Missouri State": ("Missouri St", "Bears"),
            "Monmouth": ("Monmouth", "Hawks"),
            "Montana": ("Montana", "Grizzlies"),
            "Montana State": ("Montana St", "Bobcats"),
            "Morehead State": ("Morehead St", "Eagles"),
            "Morgan State": ("Morgan St", "Bears"),
            "Mount St. Mary's": ("Mt St Mary's", "Mountaineers"),
            "Murray State": ("Murray St", "Racers"),
            "Navy": ("Navy", "Midshipmen"),
            "NC State": ("NC State", "Wolfpack"),
            "Nebraska": ("Nebraska", "Cornhuskers"),
            "Nebraska Omaha": ("Omaha", "Mavericks"),
            "Nevada": ("Nevada", "Wolf Pack"),
            "New Hampshire": ("UNH", "Wildcats"),
            "New Mexico": ("New Mexico", "Lobos"),
            "New Mexico State": ("NMSU", "Aggies"),
            "New Orleans": ("New Orleans", "Privateers"),
            "Niagara": ("Niagara", "Purple Eagles"),
            "Nicholls State": ("Nicholls", "Colonels"),
            "NJIT": ("NJIT", "Highlanders"),
            "Norfolk State": ("Norfolk St", "Spartans"),
            "North Alabama": ("UNA", "Lions"),
            "North Carolina": ("UNC", "Tar Heels"),
            "North Carolina A&T": ("NC A&T", "Aggies"),
            "North Carolina Central": ("NCCU", "Eagles"),
            "North Dakota": ("UND", "Fighting Hawks"),
            "North Dakota State": ("NDSU", "Bison"),
            "North Florida": ("UNF", "Ospreys"),
            "North Texas": ("North Texas", "Mean Green"),
            "Northeastern": ("Northeastern", "Huskies"),
            "Northern Arizona": ("NAU", "Lumberjacks"),
            "Northern Colorado": ("Northern Colo", "Bears"),
            "Northern Illinois": ("NIU", "Huskies"),
            "Northern Iowa": ("UNI", "Panthers"),
            "Northern Kentucky": ("NKU", "Norse"),
            "Northwestern": ("Northwestern", "Wildcats"),
            "Northwestern State": ("NSU", "Demons"),
            "Notre Dame": ("Notre Dame", "Fighting Irish"),
            "Oakland": ("Oakland", "Golden Grizzlies"),
            "Ohio": ("Ohio", "Bobcats"),
            "Ohio State": ("Ohio St", "Buckeyes"),
            "Oklahoma": ("Oklahoma", "Sooners"),
            "Oklahoma State": ("Oklahoma St", "Cowboys"),
            "Old Dominion": ("ODU", "Monarchs"),
            "Oral Roberts": ("ORU", "Golden Eagles"),
            "Oregon": ("Oregon", "Ducks"),
            "Oregon State": ("Oregon St", "Beavers"),
            "Pacific": ("Pacific", "Tigers"),
            "Penn State": ("Penn St", "Nittany Lions"),
            "Pennsylvania": ("Penn", "Quakers"),
            "Pepperdine": ("Pepperdine", "Waves"),
            "Pittsburgh": ("Pitt", "Panthers"),
            "Portland": ("Portland", "Pilots"),
            "Portland State": ("Portland St", "Vikings"),
            "Prairie View A&M": ("PVAMU", "Panthers"),
            "Presbyterian": ("Presbyterian", "Blue Hose"),
            "Princeton": ("Princeton", "Tigers"),
            "Providence": ("Providence", "Friars"),
            "Purdue": ("Purdue", "Boilermakers"),
            "Purdue Fort Wayne": ("PFW", "Mastodons"),
            "Quinnipiac": ("Quinnipiac", "Bobcats"),
            "Radford": ("Radford", "Highlanders"),
            "Rhode Island": ("URI", "Rams"),
            "Rice": ("Rice", "Owls"),
            "Richmond": ("Richmond", "Spiders"),
            "Rider": ("Rider", "Broncs"),
            "Robert Morris": ("RMU", "Colonials"),
            "Rutgers": ("Rutgers", "Scarlet Knights"),
            "Sacramento State": ("Sac State", "Hornets"),
            "Sacred Heart": ("Sacred Heart", "Pioneers"),
            "Saint Francis (PA)": ("St Francis PA", "Red Flash"),
            "Saint Joseph's": ("Saint Joe's", "Hawks"),
            "Saint Louis": ("Saint Louis", "Billikens"),
            "Saint Mary's": ("Saint Mary's", "Gaels"),
            "Saint Peter's": ("Saint Peter's", "Peacocks"),
            "Sam Houston State": ("SHSU", "Bearkats"),
            "Samford": ("Samford", "Bulldogs"),
            "San Diego": ("San Diego", "Toreros"),
            "San Diego State": ("SDSU", "Aztecs"),
            "San Francisco": ("San Francisco", "Dons"),
            "San Jose State": ("SJSU", "Spartans"),
            "Santa Clara": ("Santa Clara", "Broncos"),
            "Seattle": ("Seattle", "Redhawks"),
            "Seton Hall": ("Seton Hall", "Pirates"),
            "Siena": ("Siena", "Saints"),
            "South Alabama": ("South Alabama", "Jaguars"),
            "South Carolina": ("South Carolina", "Gamecocks"),
            "South Carolina State": ("SC State", "Bulldogs"),
            "South Dakota": ("USD", "Coyotes"),
            "South Dakota State": ("SDSU", "Jackrabbits"),
            "South Florida": ("USF", "Bulls"),
            "Southeast Missouri State": ("SEMO", "Redhawks"),
            "Southeastern Louisiana": ("SE Louisiana", "Lions"),
            "Southern": ("Southern", "Jaguars"),
            "Southern Illinois": ("SIU", "Salukis"),
            "Southern Miss": ("Southern Miss", "Golden Eagles"),
            "Southern Utah": ("SUU", "Thunderbirds"),
            "St. Bonaventure": ("St Bona", "Bonnies"),
            "St. John's": ("St John's", "Red Storm"),
            "Stanford": ("Stanford", "Cardinal"),
            "Stephen F. Austin": ("SFA", "Lumberjacks"),
            "Stetson": ("Stetson", "Hatters"),
            "Stony Brook": ("Stony Brook", "Seawolves"),
            "Syracuse": ("Syracuse", "Orange"),
            "TCU": ("TCU", "Horned Frogs"),
            "Temple": ("Temple", "Owls"),
            "Tennessee": ("Tennessee", "Volunteers"),
            "Tennessee State": ("TSU", "Tigers"),
            "Tennessee Tech": ("Tenn Tech", "Golden Eagles"),
            "Texas": ("Texas", "Longhorns"),
            "Texas A&M": ("Texas A&M", "Aggies"),
            "Texas Southern": ("Texas So", "Tigers"),
            "Texas State": ("Texas State", "Bobcats"),
            "Texas Tech": ("Texas Tech", "Red Raiders"),
            "Toledo": ("Toledo", "Rockets"),
            "Towson": ("Towson", "Tigers"),
            "Troy": ("Troy", "Trojans"),
            "Tulane": ("Tulane", "Green Wave"),
            "Tulsa": ("Tulsa", "Golden Hurricane"),
            "UAB": ("UAB", "Blazers"),
            "UC Davis": ("UC Davis", "Aggies"),
            "UC Irvine": ("UC Irvine", "Anteaters"),
            "UC Riverside": ("UC Riverside", "Highlanders"),
            "UC San Diego": ("UCSD", "Tritons"),
            "UC Santa Barbara": ("UCSB", "Gauchos"),
            "UCF": ("UCF", "Knights"),
            "UCLA": ("UCLA", "Bruins"),
            "UMass": ("UMass", "Minutemen"),
            "UMBC": ("UMBC", "Retrievers"),
            "UMKC": ("UMKC", "Roos"),
            "UNC Asheville": ("UNC Asheville", "Bulldogs"),
            "UNC Greensboro": ("UNCG", "Spartans"),
            "UNC Wilmington": ("UNCW", "Seahawks"),
            "UNLV": ("UNLV", "Rebels"),
            "USC": ("USC", "Trojans"),
            "USC Upstate": ("USC Upstate", "Spartans"),
            "UT Arlington": ("UTA", "Mavericks"),
            "UT Martin": ("UT Martin", "Skyhawks"),
            "UT Rio Grande Valley": ("UTRGV", "Vaqueros"),
            "UTEP": ("UTEP", "Miners"),
            "UTSA": ("UTSA", "Roadrunners"),
            "Utah": ("Utah", "Utes"),
            "Utah State": ("Utah St", "Aggies"),
            "Utah Valley": ("Utah Valley", "Wolverines"),
            "Valparaiso": ("Valpo", "Beacons"),
            "Vanderbilt": ("Vanderbilt", "Commodores"),
            "VCU": ("VCU", "Rams"),
            "Vermont": ("Vermont", "Catamounts"),
            "Villanova": ("Villanova", "Wildcats"),
            "Virginia": ("Virginia", "Cavaliers"),
            "Virginia Tech": ("Va Tech", "Hokies"),
            "VMI": ("VMI", "Keydets"),
            "Wagner": ("Wagner", "Seahawks"),
            "Wake Forest": ("Wake Forest", "Demon Deacons"),
            "Washington": ("Washington", "Huskies"),
            "Washington State": ("Wazzu", "Cougars"),
            "Weber State": ("Weber St", "Wildcats"),
            "West Virginia": ("WVU", "Mountaineers"),
            "Western Carolina": ("WCU", "Catamounts"),
            "Western Illinois": ("WIU", "Leathernecks"),
            "Western Kentucky": ("WKU", "Hilltoppers"),
            "Western Michigan": ("WMU", "Broncos"),
            "Wichita State": ("Wichita St", "Shockers"),
            "William & Mary": ("W&M", "Tribe"),
            "Winthrop": ("Winthrop", "Eagles"),
            "Wisconsin": ("Wisconsin", "Badgers"),
            "Wofford": ("Wofford", "Terriers"),
            "Wright State": ("Wright St", "Raiders"),
            "Wyoming": ("Wyoming", "Cowboys"),
            "Xavier": ("Xavier", "Musketeers"),
            "Yale": ("Yale", "Bulldogs"),
            "Youngstown State": ("YSU", "Penguins"),
        }

        for name, (short_name, mascot) in team_data.items():
            Team.objects.get_or_create(
                name=name,
                defaults={
                    "short_name": short_name,
                    "mascot": mascot,
                },
            )

        self.stdout.write(self.style.SUCCESS("Successfully seeded team data"))
