name: Main Branch CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bracket_iq
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NO_ENV_FILE: 'true'
      DEV_DOCKER_WORKFLOW: 'none'
      TEST_DB_ENGINE: 'django.db.backends.postgresql'
      TEST_DB_NAME: 'bracket_iq'
      TEST_DB_USER: 'postgres'
      TEST_DB_PASSWORD: 'postgres'
      TEST_DB_HOST: 'localhost'
      TEST_DB_PORT: '5432'
      NO_DOCKER: 'true'
      PYTHONPATH: ${{ github.workspace }}
      DJANGO_SETTINGS_MODULE: bracket_iq.settings.test
    
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install -r requirements.txt; fi
        pip install pytest pytest-django pytest-cov pytest-xdist coverage black flake8 pylint mypy django-stubs
        # Install pylint-django with specific version and dependencies
        pip install pylint-django==2.6.1 pylint-plugin-utils==0.8.2 --force-reinstall
        
    - name: Show environment info
      run: |
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Installed packages:"
        pip list
        echo "Environment variables:"
        echo "PYTHONPATH: $PYTHONPATH"
        echo "DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE"
        echo "TEST_DB_ENGINE: $TEST_DB_ENGINE"
        echo "TEST_DB_HOST: $TEST_DB_HOST"
        echo "TEST_DB_PORT: $TEST_DB_PORT"
        
    - name: Run code quality checks
      run: |
        ./scripts/check || echo "Code quality checks failed but continuing"
      
    - name: Run tests with coverage and generate report
      run: |
        ./scripts/test --coverage --report || python -m pytest bracket_iq/ --cov=bracket_iq --cov-report=html
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 7 