# backend/backend/management/commands/seed_teams.py
from django.core.management.base import BaseCommand
from backend.models import Team

class Command(BaseCommand):
    help = 'Seeds the database with team data'

    def handle(self, *args, **options):
        team_names = [
            "Abilene Christian University",
            "Air Force",
            "Akron",
            "Alabama",
            "Alabama A&M",
            "Alabama State",
            "Albany",
            "Alcorn State",
            "American University",
            "Appalachian State",
            "Arizona",
            "Arizona State",
            "Arkansas",
            "Arkansas State",
            "Arkansas–Pine Bluff",
            "Army",
            "Auburn",
            "Austin Peay",
            "Ball State",
            "Baylor",
            "Belmont",
            "Bethune–Cookman",
            "Binghamton",
            "Boise State",
            "Boston College",
            "Boston University",
            "Bowling Green",
            "Bradley",
            "Brown",
            "Bryant",
            "Bucknell",
            "Buffalo",
            "Butler",
            "BYU",
            "Cal Poly",
            "Cal State Bakersfield",
            "Cal State Fullerton",
            "Cal State Northridge",
            "California",
            "California Baptist",
            "Campbell",
            "Canisius",
            "Central Arkansas",
            "Central Connecticut",
            "Central Michigan",
            "Charleston Southern",
            "Charlotte",
            "Chattanooga",
            "Chicago State",
            "Cincinnati",
            "Citadel",
            "Clemson",
            "Cleveland State",
            "Coastal Carolina",
            "Colgate",
            "College of Charleston",
            "Colorado",
            "Colorado State",
            "Columbia",
            "Connecticut",
            "Coppin State",
            "Cornell",
            "Creighton",
            "Dartmouth",
            "Davidson",
            "Dayton",
            "Delaware",
            "Delaware State",
            "Denver",
            "DePaul",
            "Detroit Mercy",
            "Drake",
            "Drexel",
            "Duke",
            "Duquesne",
            "East Carolina",
            "East Tennessee State",
            "Eastern Illinois",
            "Eastern Kentucky",
            "Eastern Michigan",
            "Eastern Washington",
            "Elon",
            "Evansville",
            "Fairfield",
            "Fairleigh Dickinson",
            "Florida",
            "Florida A&M",
            "Florida Atlantic",
            "Florida Gulf Coast",
            "Florida International",
            "Florida State",
            "Fordham",
            "Fresno State",
            "Furman",
            "Gardner–Webb",
            "George Mason",
            "George Washington",
            "Georgetown",
            "Georgia",
            "Georgia Southern",
            "Georgia State",
            "Georgia Tech",
            "Gonzaga",
            "Grambling State",
            "Grand Canyon",
            "Green Bay",
            "Hampton",
            "Hartford",
            "Harvard",
            "Hawaii",
            "High Point",
            "Hofstra",
            "Holy Cross",
            "Houston",
            "Houston Baptist",
            "Howard",
            "Idaho",
            "Idaho State",
            "Illinois",
            "Illinois State",
            "Illinois–Chicago",
            "Incarnate Word",
            "Indiana",
            "Indiana State",
            "Iona",
            "Iowa",
            "Iowa State",
            "IUPUI",
            "Jackson State",
            "Jacksonville",
            "Jacksonville State",
            "James Madison",
            "Kansas",
            "Kansas State",
            "Kennesaw State",
            "Kent State",
            "Kentucky",
            "La Salle",
            "Lafayette",
            "Lamar",
            "Lehigh",
            "Liberty",
            "Lipscomb",
            "Long Beach State",
            "Long Island University",
            "Longwood",
            "Louisiana",
            "Louisiana Tech",
            "Louisiana–Monroe",
            "Louisville",
            "Loyola (MD)",
            "Loyola (IL)",
            "Loyola Marymount",
            "LSU",
            "Maine",
            "Manhattan",
            "Marist",
            "Marquette",
            "Marshall",
            "Maryland",
            "Maryland Eastern Shore",
            "UMass Lowell",
            "McNeese State",
            "Memphis",
            "Mercer",
            "Merrimack",
            "Miami (FL)",
            "Miami (OH)",
            "Michigan",
            "Michigan State",
            "Middle Tennessee",
            "Milwaukee",
            "Minnesota",
            "Mississippi State",
            "Mississippi Valley State",
            "Missouri",
            "Missouri State",
            "Monmouth",
            "Montana",
            "Montana State",
            "Morehead State",
            "Morgan State",
            "Mount St. Mary's",
            "Murray State",
            "Navy",
            "NC State",
            "Nebraska",
            "Nebraska Omaha",
            "Nevada",
            "New Hampshire",
            "New Mexico",
            "New Mexico State",
            "New Orleans",
            "Niagara",
            "Nicholls State",
            "NJIT",
            "Norfolk State",
            "North Alabama",
            "North Carolina",
            "North Carolina A&T",
            "North Carolina Central",
            "North Dakota",
            "North Dakota State",
            "North Florida",
            "North Texas",
            "Northeastern",
            "Northern Arizona",
            "Northern Colorado",
            "Northern Illinois",
            "Northern Iowa",
            "Northern Kentucky",
            "Northwestern",
            "Northwestern State",
            "Notre Dame",
            "Oakland",
            "Ohio",
            "Ohio State",
            "Oklahoma",
            "Oklahoma State",
            "Old Dominion",
            "Oral Roberts",
            "Oregon",
            "Oregon State",
            "Pacific",
            "Penn State",
            "Pennsylvania",
            "Pepperdine",
            "Pittsburgh",
            "Portland",
            "Portland State",
            "Prairie View A&M",
            "Presbyterian",
            "Princeton",
            "Providence",
            "Purdue",
            "Purdue Fort Wayne",
            "Quinnipiac",
            "Radford",
            "Rhode Island",
            "Rice",
            "Richmond",
            "Rider",
            "Robert Morris",
            "Rutgers",
            "Sacramento State",
            "Sacred Heart",
            "Saint Francis (PA)",
            "Saint Joseph's",
            "Saint Louis",
            "Saint Mary's",
            "Saint Peter's",
            "Sam Houston State",
            "Samford",
            "San Diego",
            "San Diego State",
            "San Francisco",
            "San Jose State",
            "Santa Clara",
            "Savannah State",
            "Seattle",
            "Seton Hall",
            "Siena",
            "SIU Edwardsville",
            "SMU",
            "South Alabama",
            "South Carolina",
            "South Carolina State",
            "South Dakota",
            "South Dakota State",
            "South Florida",
            "Southeast Missouri State",
            "Southeastern Louisiana",
            "Southern",
            "Southern Illinois",
            "Southern Miss",
            "Southern Utah",
            "St. Bonaventure",
            "St. Francis Brooklyn",
            "St. John's",
            "Stanford",
            "Stephen F. Austin",
            "Stetson",
            "Stony Brook",
            "Syracuse",
            "TCU",
            "Temple",
            "Tennessee",
            "Tennessee State",
            "Tennessee Tech",
            "Texas",
            "Texas A&M",
            "Texas A&M-Corpus Christi",
            "Texas Southern",
            "Texas State",
            "Texas Tech",
            "The Citadel",
            "Toledo",
            "Towson",
            "Troy",
            "Tulane",
            "Tulsa",
            "UAB",
            "UC Davis",
            "UC Irvine",
            "UC Riverside",
            "UC San Diego",
            "UC Santa Barbara",
            "UCLA",
            "UMass",
            "UMBC",
            "UNC Asheville",
            "UNC Greensboro",
            "UNC Wilmington",
            "UNCG",
            "UNLV",
            "USC",
            "USC Upstate",
            "UT Arlington",
            "UT Martin",
            "UT Rio Grande Valley",
            "Utah",
            "Utah State",
            "Utah Valley",
            "UTEP",
            "UTSA",
            "Valparaiso",
            "Vanderbilt",
            "VCU",
            "Vermont",
            "Villanova",
            "Virginia",
            "Virginia Tech",
            "VMI",
            "Wagner",
            "Wake Forest",
            "Washington",
            "Washington State",
            "Weber State",
            "West Virginia",
            "Western Carolina",
            "Western Illinois",
            "Western Kentucky",
            "Western Michigan",
            "Wichita State",
            "William & Mary",
            "Winthrop",
            "Wisconsin",
            "Wofford",
            "Wright State",
            "Wyoming",
            "Xavier",
            "Yale",
            "Youngstown State",
        ]

        for name in team_names:
            Team.objects.create(name=name)

        self.stdout.write(self.style.SUCCESS('Successfully seeded team data'))